version: '3.4'

services:
  question_answer_app:
    image: question_answer_app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MONGODB_URL: mongodb://mongo:27017/question-answer-app
      PORT: 3000
    ports:
      - 3000:3000
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - 27017:27017