swagger: "2.0"

info:
  title: StackOverFlow Project APIs
  description: Batch 3 - Case Study Project API documentation
  version: 1.0
  termsOfService: 'https://swagger.io/terms/'
  contact:
    email: sachinsom743@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/license/LIS'
  servers:
    -url: http:/localhost:3000
    description: Local Development Server

schemes: [http, https]

securityDefinitions:
  # Authorization For JWT
  bearerAuth:
    type: apiKey
    name: Authorization
    sheme: bearer
    bearerFormat: JWT

definitions:
  NewUser:
    type: object
    required:
      - name
      - username
      - email
      - password
    properties:
      name:
        type: string
      username:
        type: string
      email:
        type: string
      password:
        type: string

  UserDetails:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string

  Question:
    type: object
    required:
      - title
      - body
    properties:
      title:
        type: string
      body:
        type: string
  Answer:
    type: object
    required:
      - question-id
      - answer
    properties:
      question-id:
        type: integer
      answer:
        type: string
  QuestionID:
    type: object
    required:
      - question-id
    properties:
      question-id:
        type: integer

tags:
- name: "User"
  description: "APIs Related to User"
- name: "Question"
  description: "APIs related to Questions."
- name: "Answer"
  description: "APIs related to Answer."
schemes:
- "http"
- "https"

paths:
  /users/registration:
    post:
      tags:
        - "User"
      summary: Creates a new user
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        '201':
          description: Created
        '201':
          description: Not Acceptable
        '500':
          description: Internal Server Error

  /users/login:
    post:
      tags:
        - "User"
      summary: Login User
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserDetails'
      responses:
        '201':
          description: Created
        '201':
          description: Not Acceptable
        '500':
          description: Internal Server Error

  /users:
    get:
      tags:
        - "User"
      security:
        - bearerAuth: []
      summary: Get User Profile
      produces:
        - application/json
      security:
        - bearerAuth : []
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Internal Server Error


  /question/ask:
    post:
      tags:
        - Question
      summary: Ask Question
      security:
        - bearerAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            type: body
            properties:
              user-details:
                $ref: '#/definitions/UserDetails'
              question:
                $ref: '#/definitions/Question'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Internal Server Error


  /question/{questionId}/answer:
    post:
      summary: Add Answer of a Question
      tags:
        - Answer
      security:
        - bearerAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: questionId
          schema:
            type: integer
        - in: body
          name: body
          schema:
            type: object
            properties:
              user-details:
                $ref: '#/definitions/UserDetails'
              question:
                $ref: '#/definitions/Answer'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Internal Server Error

  /question/{questionID}/answer:
    put:
      summary: Edit an answer
      tags:
        - Answer
      security:
        - bearerAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: questionID
          schema:
            type: integer
        - in: body
          name: body
          schema:
            type: object
            properties:
              user-details:
                $ref: '#/definitions/UserDetails'
              question:
                $ref: '#/definitions/Answer'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Internal Server Error


  /question/{questionId}:
    put:
      tags:
        - Question
      summary: Edit a question
      security:
        - bearerAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: questionId
          schema:
            required:
              - questionId
            properties:
              questionId:
                type: integer
        - in: body
          name: body
          schema:
            type: body
            properties:
              user-details:
                $ref: '#/definitions/UserDetails'
              question:
                $ref: '#/definitions/Question'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Internal Server Error

  /question/{questionId}/answer/{answerId}/upvote:
    put:
      tags:
        - Answer
      summary: UpVote an answer
      security:
        - bearerAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: questionId
          schema:
            required:
              - questionId
            properties:
              questionId:
                type: integer
        - in: path
          name: answerId
          schema:
            required:
              - answerId
            properties:
              answerId:
                type: integer
        - in: body
          name: body
          schema:
            type: object
            properties:
              user-details:
                $ref: '#/definitions/UserDetails'
              question:
                $ref: '#/definitions/QuestionID'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Internal Server Error

  /question/{questionId}/answer/{answerId}/downvote:
    put:
      tags:
        - Answer
      summary: DownVote an answer
      security:
        - bearerAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: questionId
          schema:
            required:
              - questionId
            questionId:
              type: integer
        - in: path
          name: answerId
          schema:
            required:
              - answerId
            answerId:
              type: integer
        - in: body
          name: body
          schema:
            type: object
            properties:
              user-details:
                $ref: '#/definitions/UserDetails'
              question:
                $ref: '#/definitions/QuestionID'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Internal Server Error

  /question/{answerId}/upvote:
    put:
      summary: Upvote a question
      tags:
        - Question
      security:
        - bearerAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: answerId
          required:
            - answerId
          schema:
            answerId:
              type: integer
        - in: body
          name: body
          schema:
            type: object
            properties:
              user-details:
                $ref: '#/definitions/UserDetails'
      responses:
        '201':
          description: 'Created'
        '401':
          description: 'Unauthorized'
        '406':
          description: 'Not Acceptable'
        '501':
          description: 'Internal Server Error'

  /question/{answerId}/downvote:
    put:
      summary: DownVote a question
      tags:
        - Question
      security:
        - bearerAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: answerId
          required:
            - answerId
          schema:
            answerId:
              type: integer
        - in: body
          name: body
          schema:
            type: object
            properties:
              user-details:
                $ref: '#/definitions/UserDetails'
      responses:
        '201':
          description: 'Created'
        '401':
          description: 'Unauthorized'
        '406':
          description: 'Not Acceptable'
        '501':
          description: 'Internal Server Error'

  /question/all:
    get:
      summary: All questions asked by user
      tags:
        - User
        - Question
      security:
        - bearerAuth: []
      produces:
        - application/json
      responses:
        '200':
          description: 'Ok'
        '201':
          description: 'Created'
        '401':
          description: 'Unauthorized'
        '406':
          description: 'Not Acceptable'
        '501':
          description: 'Internal Server Error'

  /question/{answerId}/answers:
    get:
      summary: All answers of a particular question
      tags:
        - Answer
      security:
        - bearerAuth: []
      produces:
        - application/json
      parameters:
        - in: path
          name: answerId
          required:
            - answerId
          properties:
            answerId:
              type: integer
      responses:
        '200':
          description: 'Ok'
        '201':
          description: 'Created'
        '401':
          description: 'Unauthorized'
        '406':
          description: 'Not Acceptable'
        '501':
          description: 'Internal Server Error'




