const CREATED_HTTP_STATUS_CODE = 201;
const BAD_REQUEST_HTTP_STATUS_CODE = 400;
const UNAUTHORIZED_HTTP_STATUS_CODE = 401;

module.exports = {
  CREATED_HTTP_STATUS_CODE,
  BAD_REQUEST_HTTP_STATUS_CODE,
  UNAUTHORIZED_HTTP_STATUS_CODE,
};
